###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  memcached:
    image: "memcached:alpine"

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "42001:8025"

  mariadb:
    image: "mariadb:11.0"
    working_dir: /backend
    volumes:
      - "./back.tasks:/backend"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test-db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test1234
    ports:
      - "42003:3306"

  webserver:
    image: "nginx:alpine"
    working_dir: /backend
    volumes:
      - "./back.tasks:/backend"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "42000:80"

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /backend
    volumes:
      - "./back.tasks:/backend"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini"

  # NOT TESTED FROM HERE DOWN

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "42002:80"
    depends_on:
      - mariadb

  frontend: # Frontend has Dockerfile
    build: ./tasks/Dockerfile
    working_dir: /frontend
    volumes:
      - "./front.tasks:/frontend"
    ports:
      - "9000:9000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - webserver
